# Site settings
title: Wat? Oh ok I get...
header-img: img/home-bg.png
email: rmody3@gmail.com
copyright_name: rmody3
description: > # this means to ignore newlines until "baseurl:"
  A blog about interesting thing in development and tech
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: RahulTMody
github_username:  rmody3
learn_profile: rmody3
email_username: rmody3@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
